image: node:18

stages:
    - build
    - codequality
    - clienttest
#    - servertest

before_script:
    - npm run setup:ci

build:
    stage: build
    script:
        - npm run build
    artifacts:
        paths:
            - dist/
    retry: 1

Prettier check:
    stage: codequality
    script:
        - npm run format:check
    retry: 1

Eslint:
    stage: codequality
    script:
        - npm run lint
    retry: 1

Unit test:
    stage: clienttest
    script:
        - npm run test:client
    retry: 1
    dependencies:
        - build
        - Prettier check
        - Eslint
# Skipping since "libcrypto.so.1.1" is missing in image node:20
# Server test:
#     stage: servertest
#     script:
#         - npm run test:server
#     retry: 1
#     dependencies:
#         - build
#         - Prettier check
#         - Eslint
