image: node:18

stages:
    - build
    - codequality
    - clienttest
    - backendtest

before_script:
    - cd client
    - npm install
    - npm install --save-dev jest@latest
    - npm i --save-dev @types/jest

build:
    stage: build
    script:
        - npm run build
    artifacts:
        paths:
            - dist/
    retry: 1

Prettier check:
    stage: codequality
    script:
        - npm run format-check
    retry: 1

Eslint:
    stage: codequality
    script:
        - npm run lint
    retry: 1

Unittest:
    stage: clienttest
    script: 
        - npm run test
    retry: 1
    dependencies:
        - build
        - Prettier check
        - Eslint